#!/usr/bin/env sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
doc="${repo_root}/docs/real-integration-cases.md"

assert_contains() {
  needle="$1"
  if ! grep -F -- "$needle" "$doc" >/dev/null 2>&1; then
    echo "expected $doc to contain: $needle" >&2
    exit 1
  fi
}

assert_contains "scripts/showcase-agent-onboarding-report.sh"
assert_contains "TESTLOOP_MCP_VERIFY_EXPECT_VERSION=0.5.7"
assert_contains "TESTLOOP_MCP_VERSION=v0.5.7"
assert_contains "scripts/run-first-run-ci.sh"
assert_contains "scripts/run-onboarding-ci.sh"
assert_contains "scripts/showcase-laoxia-scaffold-report.sh"
assert_contains "/tmp/testloop-laoxia-server-first-run"
assert_contains "/tmp/testloop-laoxia-web-first-run"
assert_contains "/tmp/testloop-laoxia-server-onboarding"
assert_contains "/tmp/testloop-laoxia-web-onboarding"
assert_contains "/tmp/testloop-laoxia-scaffold"
assert_contains "/tmp/testloop-laoxia-server-onboarding-artifact-verify"
assert_contains "/tmp/testloop-laoxia-web-onboarding-artifact-verify"
assert_contains "first_run_agent_next_step=ready"
assert_contains "first-run-context.txt"
assert_contains "first-run.log"
assert_contains "testloop-mcp 0.5.7"
assert_contains "testloop-mcp 0.5.13"
assert_contains "v0.5.19 客户端 release smoke 实跑记录"
assert_contains "scripts/showcase-agent-decision-client-release-smoke.sh --json"
assert_contains "curl: (56) Recv failure: Operation timed out"
assert_contains "curl: (56) Send failure: Broken pipe"
assert_contains "curl --retry"
assert_contains "--retry-all-errors"
assert_contains "release_ref=v0.5.19"
assert_contains "helper_refs.install=v0.5.19"
assert_contains "helper_refs.consumer=v0.5.19"
assert_contains "agent_next_steps.client=ready"
assert_contains "agent_next_steps.consumer=ready"
assert_contains "agent_artifact_status=passed"
assert_contains 'Artifact verification: `passed`'
assert_contains "section_signal=独立 CLI 生成动作 smoke action=manual_review"
assert_contains "laoxia server 覆盖率任务闭环样例"
assert_contains "TESTLOOP_VALIDATE_GO_FILE_FILTER=utils"
assert_contains "scripts/validate-go-coverage-top-tasks.sh"
assert_contains "/tmp/testloop-laoxia-agent-loop.jsonl"
assert_contains "status_counts\":{\"passed\":1"
assert_contains "action_counts\":{\"ready\":1"
assert_contains "zero_skip\":1"
assert_contains "skipped_total\":0"
assert_contains "./fixtures/real-project-agent-loop/laoxia-server-go-utils.json"
assert_contains "SliceMapper0"
assert_contains "utils/alias.go"
assert_contains "generated_cases"
assert_contains "run_result.action=ready"
assert_contains "原始 JSONL 不入仓"
assert_contains "mcp-hub 历史 repair 回归样例"
assert_contains "TESTLOOP_VALIDATE_JS_TASKS_FILE=/Users/binlee/code/open-source/testloop-mcp/testdata/js-mcp-hub/repair-tasks.jsonl"
assert_contains "TESTLOOP_VALIDATE_JS_TASK_IDS=vitest-mcp-hub-repair-1"
assert_contains "scripts/validate-js-coverage-top-tasks.sh"
assert_contains "/tmp/testloop-mcp-hub-repair-agent-loop.jsonl"
assert_contains "ConfigManager.loadConfig"
assert_contains "src/utils/config.js"
assert_contains "./fixtures/real-project-agent-loop/mcp-hub-vitest-repair.json"
assert_contains "repair_generated_test"
assert_contains "haoy-apk-station 环境手审样例"
assert_contains "TESTLOOP_VALIDATE_PY_TASKS_FILE=/Users/binlee/code/open-source/testloop-mcp/testdata/py-haoy-apk-station/environment-tasks.jsonl"
assert_contains "TESTLOOP_VALIDATE_PY_TASK_IDS=pytest-apk-frontend-env-1"
assert_contains "scripts/validate-py-coverage-top-tasks.sh"
assert_contains "/tmp/testloop-haoy-apk-manual-review-agent-loop.jsonl"
assert_contains "manual_review_environment"
assert_contains "serve_frontend"
assert_contains "app/main.py"
assert_contains "./fixtures/real-project-agent-loop/haoy-apk-station-py-environment.json"
assert_contains "haoy-apk-station 外部服务手审样例"
assert_contains "TESTLOOP_VALIDATE_PY_TASKS_FILE=/Users/binlee/code/open-source/testloop-mcp/testdata/py-haoy-apk-station/external-service-tasks.jsonl"
assert_contains "TESTLOOP_VALIDATE_PY_TASK_IDS=pytest-apk-download-external-1"
assert_contains "scripts/py-external-service-runner.py"
assert_contains "/tmp/testloop-haoy-apk-external-service-agent-loop.jsonl"
assert_contains "manual_review_external_service"
assert_contains "download_apk"
assert_contains "app/api/apps.py"
assert_contains "./fixtures/real-project-agent-loop/haoy-apk-station-py-external-service.json"
assert_contains "TESTLOOP_REPORT_PROJECT_DIR"
assert_contains "TESTLOOP_REPORT_PROJECT_COMMAND"
assert_contains "/tmp/testloop-laoxia-server-onboarding-v0.5.4"
assert_contains "/tmp/testloop-laoxia-web-onboarding-v0.5.4"
assert_contains "overall_status=passed"
assert_contains "failed_count=0"
assert_contains "agent_next_step=ready"
assert_contains "fix-installation"
assert_contains "inspect-user-project"

echo "real integration cases doc test passed"
